name: gest_inventory
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  open_file: ^3.1.0
  intl: ^0.17.0
  flutter_multiselect:
  syncfusion_flutter_pdf: ^20.1.50-beta
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.1.1
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_dynamic_links: ^4.0.7
  firebase_messaging: ^12.0.1
  firebase_storage: ^10.2.8
  cloud_firestore: ^3.4.7
  flutter_phoenix: ^1.0.0
  flutter_native_splash: ^2.1.2+1
  flutter_svg: ^0.22.0
  flutter_barcode_scanner: ^2.0.0
  quiver: ^3.0.1+1
  future_progress_dialog: ^0.2.0
  email_validator: ^2.1.17
  fluttertoast: ^8.0.9
  adaptive_dialog: ^1.6.3
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  path: ^1.8.1
  fluid_dialog: ^1.0.0
  image_picker: ^0.8.5+3
  flutter_speed_dial: ^6.0.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  #flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.10.0"

flutter_icons:
    android: true
    ios: true
    image_path_android: "lib/assets/icon/ic_launcher.png"
    image_path_ios: "lib/assets/icon/ic_launcher.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/icon/blue-icon.png
    - lib/assets/gi-blue.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
