/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData receipt_long = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitoring = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_as_pdf = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playlist_add = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData best_sales = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode_scanner = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_ccw = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_slash = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_boxes = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xf02a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_up = IconData(0xf160, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_down = IconData(0xf161, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_up = IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_down = IconData(0xf163, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxes = IconData(0xf468, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_open = IconData(0xf49e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_register = IconData(0xf788, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
