import 'package:flutter/material.dart';
import 'custom_icons.dart';

final _icons = <AppIcons, IconData>{
  AppIcons.search: Icons.search,
  AppIcons.price: Icons.monetization_on_outlined,
  AppIcons.user: CustomIcons.user,
  AppIcons.edit: Icons.edit,
  AppIcons.qr: Icons.qr_code,
  AppIcons.add: Icons.add,
  AppIcons.remove: Icons.remove,
  AppIcons.barcode: CustomIcons.barcode,
  AppIcons.scanner: CustomIcons.barcode_scanner,
  AppIcons.google: CustomIcons.google,
  AppIcons.delete_user: Icons.person_remove,
  AppIcons.gen_pdf: CustomIcons.picture_as_pdf,
  AppIcons.change: CustomIcons.arrows_ccw,
  AppIcons.arrow_back: Icons.arrow_back,
  AppIcons.show: Icons.visibility,
  AppIcons.hide: Icons.visibility_off,
  AppIcons.error: Icons.clear,
  AppIcons.ok: Icons.check,
  AppIcons.email: Icons.email_outlined,
  AppIcons.password: Icons.https_outlined,
  AppIcons.person: Icons.person,
  AppIcons.phone: Icons.phone_outlined,
  AppIcons.salary: Icons.attach_money_outlined,
  AppIcons.quantity: Icons.numbers_outlined,
  AppIcons.signup: Icons.person_add,
  AppIcons.arrow_down: Icons.keyboard_arrow_down,
  AppIcons.admin: Icons.security,
  AppIcons.take_photo: Icons.add_a_photo_outlined,
  AppIcons.pick_photo: Icons.add_photo_alternate_outlined,
  AppIcons.delete_photo: Icons.delete_forever_outlined,
  AppIcons.add_photo: Icons.add_a_photo,
  AppIcons.save: Icons.save_rounded,
  AppIcons.text: Icons.abc_outlined,
  AppIcons.address: Icons.location_on_outlined,
  AppIcons.city: Icons.location_city_outlined,
  AppIcons.login: Icons.login_outlined,
  AppIcons.logout: Icons.logout_outlined,
  AppIcons.menu: Icons.menu,
  AppIcons.store: Icons.store,
  AppIcons.store_slash: CustomIcons.store_slash,
  AppIcons.store_add: Icons.add_business,
  AppIcons.shopping: CustomIcons.cash_register,
  AppIcons.list: Icons.list,
  AppIcons.edit_product: CustomIcons.box_open,
  AppIcons.products: CustomIcons.boxes,
  AppIcons.add_product: CustomIcons.add_boxes,
  AppIcons.sales: CustomIcons.best_sales,
  AppIcons.statics: CustomIcons.monitoring,
  AppIcons.inform: CustomIcons.receipt_long,
  AppIcons.employees: Icons.group,
  AppIcons.next: Icons.arrow_forward_ios_outlined,
  AppIcons.options: Icons.more_vert,
  AppIcons.delete: Icons.delete_forever_rounded,
  AppIcons.pay: CustomIcons.cash,
  AppIcons.sort_up: CustomIcons.sort_up,
  AppIcons.sort_down: CustomIcons.sort_down,
  AppIcons.sort_amount_up: CustomIcons.sort_amount_up,
  AppIcons.sort_amount_down: CustomIcons.sort_amount_down,
};

Icon getIcon(AppIcons icon, {Color? color, double? size}) {
  return Icon(
    _icons[icon],
    color: color,
    size: size,
  );
}

IconData? getIconData(AppIcons icon) {
  return _icons[icon];
}

enum AppIcons {
  search,
  price,
  user,
  edit,
  add,
  remove,
  qr,
  barcode,
  scanner,
  google,
  delete_user,
  gen_pdf,
  change,
  arrow_back,
  show,
  hide,
  ok,
  error,
  email,
  password,
  person,
  phone,
  salary,
  quantity,
  signup,
  arrow_down,
  admin,
  take_photo,
  pick_photo,
  delete_photo,
  add_photo,
  save,
  text,
  address,
  city,
  login,
  logout,
  menu,
  store,
  store_slash,
  store_add,
  shopping,
  list,
  edit_product,
  products,
  add_product,
  sales,
  inform,
  statics,
  employees,
  next,
  options,
  delete,
  pay,
  sort_up,
  sort_down,
  sort_amount_up,
  sort_amount_down,
}
